# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmnt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pst', models.TextField()),
                ('image', models.ImageField(default=None, upload_to=b'')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('job', models.CharField(blank=True, max_length=255)),
                ('workplace', models.CharField(blank=True, max_length=255)),
                ('education', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('birthplace', models.CharField(blank=True, max_length=255)),
                ('is_logged_in', models.BooleanField(default=False, max_length=255)),
                ('image', models.ImageField(default=None, upload_to=b'')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('friend1', models.ManyToManyField(related_name='friend2', to='fb.Users')),
            ],
        ),
        migrations.AddField(
            model_name='thread',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='fb.Users'),
        ),
        migrations.AddField(
            model_name='thread',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='fb.Users'),
        ),
        migrations.AddField(
            model_name='post',
            name='pstreceiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pstsender', to='fb.Users'),
        ),
        migrations.AddField(
            model_name='post',
            name='pstsender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pstreceiver', to='fb.Users'),
        ),
        migrations.AddField(
            model_name='message',
            name='msgreceiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msgsender', to='fb.Users'),
        ),
        migrations.AddField(
            model_name='message',
            name='msgsender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msgreceiver', to='fb.Users'),
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='fb.Thread'),
        ),
        migrations.AddField(
            model_name='comment',
            name='cmntsender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmntreceiver', to='fb.Users'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='fb.Post'),
        ),
    ]
